baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'com.jamwheeler.com.hugo.blog'
buildFuture = true

[[menus.main]]
name = 'Daily'
pageRef = '/daily'
weight = 10
